version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/games-library
       - gamesDB:/var/lib/postgresql/games-library # Nuevo volumen para la base de datos "games-library"
    env_file:
      - ./app.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
volumes:
  progresDB:
  gamesDB: # Nuevo volumen para la base de datos "games-library"